name: Reusable CI Workflow

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environement to run the tests on'
        type: string
        required: true
    secrets:
      environment:
        description: 'The environement to run the tests on'
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          echo "${{inputs.environment}}"
          echo "${{secrets.environment}}"
